
CREATE TABLE public.TB_PAIS (
                ID_PAIS INTEGER NOT NULL,
                NM_PAIS VARCHAR NOT NULL,
                NR_POPULACAO INTEGER NOT NULL,
                CONSTRAINT id_pais PRIMARY KEY (ID_PAIS)
);


CREATE TABLE public.TB_EQUIPE (
                ID_EQUIPE INTEGER NOT NULL,
                ID_PAIS INTEGER NOT NULL,
                NM_EQUIPE INTEGER NOT NULL,
                CONSTRAINT id_equipe PRIMARY KEY (ID_EQUIPE, ID_PAIS)
);


CREATE TABLE public.TB_PILOTO (
                ID_PILOTO INTEGER NOT NULL,
                ID_PAIS INTEGER NOT NULL,
                ID_EQUIPE INTEGER NOT NULL,
                NM_PILOTO VARCHAR NOT NULL,
                DT_NASCIMENTO DATE NOT NULL,
                CONSTRAINT id_piloto PRIMARY KEY (ID_PILOTO, ID_PAIS, ID_EQUIPE)
);


CREATE TABLE public.TB_CIRCUITO (
                ID_CIRCUITO INTEGER NOT NULL,
                ID_PAIS INTEGER NOT NULL,
                NM_CIRCUITO VARCHAR NOT NULL,
                NR_EXTENSAO INTEGER NOT NULL,
                CONSTRAINT id_circuito PRIMARY KEY (ID_CIRCUITO, ID_PAIS)
);


CREATE TABLE public.TB_PROVA (
                ID_PROVA INTEGER NOT NULL,
                ID_CIRCUITO INTEGER NOT NULL,
                ID_PAIS INTEGER NOT NULL,
                DT_PROVA DATE NOT NULL,
                NM_SITUACAO VARCHAR NOT NULL,
                CONSTRAINT id_prova PRIMARY KEY (ID_PROVA, ID_CIRCUITO, ID_PAIS)
);


CREATE TABLE public.TB_RESULTADO (
                ID_PROVA INTEGER NOT NULL,
                ID_CIRCUITO INTEGER NOT NULL,
                ID_PAIS INTEGER NOT NULL,
                ID_PILOTO INTEGER NOT NULL,
                ID_EQUIPE INTEGER NOT NULL,
                NR_TEMPO_PROVA INTEGER NOT NULL,
                NR_MELHOR_VOLTA INTEGER NOT NULL,
                NR_COLOC_FINAL INTEGER NOT NULL,
                NR_POSICAO_GRID INTEGER NOT NULL,
                CONSTRAINT id_resultado PRIMARY KEY (ID_PROVA, ID_CIRCUITO, ID_PAIS, ID_PILOTO, ID_EQUIPE)
);


ALTER TABLE public.TB_CIRCUITO ADD CONSTRAINT tb_pais_tb_circuito_fk
FOREIGN KEY (ID_PAIS)
REFERENCES public.TB_PAIS (ID_PAIS)
ON DELETE CASCADE
ON UPDATE CASCADE
NOT DEFERRABLE;

ALTER TABLE public.TB_EQUIPE ADD CONSTRAINT tb_pais_tb_equipe_fk
FOREIGN KEY (ID_PAIS)
REFERENCES public.TB_PAIS (ID_PAIS)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.TB_PILOTO ADD CONSTRAINT tb_pais_tb_piloto_fk
FOREIGN KEY (ID_PAIS)
REFERENCES public.TB_PAIS (ID_PAIS)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.TB_PILOTO ADD CONSTRAINT tb_equipe_tb_piloto_fk
FOREIGN KEY (ID_EQUIPE, ID_PAIS)
REFERENCES public.TB_EQUIPE (ID_EQUIPE, ID_PAIS)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.TB_RESULTADO ADD CONSTRAINT tb_piloto_tb_resultado_fk
FOREIGN KEY (ID_PILOTO, ID_PAIS, ID_EQUIPE)
REFERENCES public.TB_PILOTO (ID_PILOTO, ID_PAIS, ID_EQUIPE)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.TB_PROVA ADD CONSTRAINT tb_circuito_tb_prova_fk
FOREIGN KEY (ID_CIRCUITO, ID_PAIS)
REFERENCES public.TB_CIRCUITO (ID_CIRCUITO, ID_PAIS)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.TB_RESULTADO ADD CONSTRAINT tb_prova_tb_resultado_fk
FOREIGN KEY (ID_PROVA, ID_CIRCUITO, ID_PAIS)
REFERENCES public.TB_PROVA (ID_PROVA, ID_CIRCUITO, ID_PAIS)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;
